<?php
/*
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GNU General Public License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/gpl-license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@refersion.com so we can send you a copy immediately.
 *
 * @category   UBERCX
 * @package    Ubercx_Addressvalidator
 * @copyright  Copyright (c) 2015 Ubercx, Inc.
 * @author	   Ubercx Developer <ubercx_nospam@jframeworks.com>
 * @license    http://opensource.org/licenses/gpl-license GNU General Public License
 */

$storeId = Mage::app()->getStore()->getId();

?>
<script type="text/javascript" > 
var html = '<div id="ubercx_addr_correction" class="" style="display: none;"><ul class="messages"><li class="error-msg"><ul><li><span>There appears to be a problem with the address. Please correct or select one below.</span></li></ul></li></ul><div id="ubercx_orig_addr"><div id="ubercx_addr_radio" class="ubercx-addr-radio"></div><div style="display: none;" id="ubercx_orig_placeholder"></div></div></div>';

var html_ship = '<div id="ubercx_ship_addr_correction" class="" style="display: none;"><ul class="messages"><li class="error-msg"><ul><li><span>There appears to be a problem with the address. Please correct or select one below.</span></li></ul></li></ul><div id="ubercx_ship_orig_addr"><div id="ubercx_ship_addr_radio" class="ubercx-addr-radio"></div><div style="display: none;" id="ubercx_ship_orig_placeholder"></div></div></div>';

$('co-billing-form').innerHTML = html+$('co-billing-form').innerHTML;
$('co-shipping-form').innerHTML = html_ship+$('co-shipping-form').innerHTML;
</script>
<script src="<?php echo $this->getSkinUrl('js/ubercx/response_handler.js') ?>"></script>

